In [1]:
import numpy as np

In [4]:
A = np.random.randint(0,10,size=(3,4))
A

array([[8, 2, 9, 7],
       [6, 3, 5, 9],
       [3, 5, 4, 8]])

In [5]:
B = np.random.randint(10,size=(4,5))
B

array([[9, 0, 8, 2, 6],
       [3, 7, 3, 9, 8],
       [8, 5, 5, 7, 6],
       [5, 5, 7, 7, 7]])

### Matrix multiplication 

In [7]:
# matrix multiplication 

C = A@B
C

array([[185,  94, 164, 146, 167],
       [148,  91, 145, 137, 153],
       [114,  95, 115, 135, 138]])

In [8]:
# mat mul using eistein sum 
# a_ij, b_jk -> c_ik
C_1 = np.einsum("ij,jk -> ik", A, B)
C_1

array([[185,  94, 164, 146, 167],
       [148,  91, 145, 137, 153],
       [114,  95, 115, 135, 138]])

### Element wise multiplication 


In [11]:
D = np.random.randint(10,size=(4,5))

E = B * D
E

array([[81,  0, 48, 14, 12],
       [12, 56, 15, 81, 40],
       [24, 40, 45, 35, 36],
       [ 0,  0, 63,  0, 21]])

In [13]:
# using einsum 
E_1 = np.einsum("ij, ij -> ij", B, D)
E_1

array([[81,  0, 48, 14, 12],
       [12, 56, 15, 81, 40],
       [24, 40, 45, 35, 36],
       [ 0,  0, 63,  0, 21]])

### Transpose 



In [14]:
A_T = np.transpose(A)
A_T

array([[8, 6, 3],
       [2, 3, 5],
       [9, 5, 4],
       [7, 9, 8]])

In [15]:
# using einsum 

A_T = np.einsum("ij -> ji", A)
A_T

array([[8, 6, 3],
       [2, 3, 5],
       [9, 5, 4],
       [7, 9, 8]])

### More complex matrix multiplication tasks 

* The ***np.einsum()*** is very convenient  for complex matrix multiplication tasks which involves matrix multiplication only along certain axis

* Sometimes **einsum()** is little more expressive when the task is complex 

Ex-01

In [16]:
A = np.random.randint(10, size=(2,3,4))
B = np.random.randint(10, size=(2,4,5))

In [17]:
A

array([[[5, 1, 2, 2],
        [0, 1, 4, 2],
        [7, 5, 0, 8]],

       [[6, 4, 2, 7],
        [4, 3, 3, 8],
        [1, 8, 2, 9]]])

In [18]:
B

array([[[9, 7, 7, 1, 7],
        [0, 1, 3, 8, 4],
        [1, 2, 9, 4, 1],
        [9, 3, 3, 3, 1]],

       [[2, 3, 6, 2, 0],
        [6, 0, 4, 5, 6],
        [8, 7, 6, 0, 8],
        [0, 1, 7, 7, 2]]])

In [21]:
# using numy 

C = np.matmul(A,B)
C

array([[[ 65,  46,  62,  27,  43],
        [ 22,  15,  45,  30,  10],
        [135,  78,  88,  71,  77]],

       [[ 52,  39, 113,  81,  54],
        [ 50,  41, 110,  79,  58],
        [ 66,  26, 113, 105,  82]]])

In [22]:
# using einstein sum 

C = np.einsum("ijk, ikl -> ijl", A,B)
C

array([[[ 65,  46,  62,  27,  43],
        [ 22,  15,  45,  30,  10],
        [135,  78,  88,  71,  77]],

       [[ 52,  39, 113,  81,  54],
        [ 50,  41, 110,  79,  58],
        [ 66,  26, 113, 105,  82]]])

Ex -02

In [23]:
# we can't multiply A and B 

A = np.random.randint(10,size=(1,4,8)) # we need to reshape from (1,4,8) -> (1,4,4,2)
B = np.random.randint(10,size=(1,4,4)) # we need to reshape this (1,4,4) -> (1,4,4,1)

# let's reshape A and B (this reshaping has some meaning)

AR = A.reshape(1,4,4,2)
BR = B.reshape(1,4,4,1)

In [24]:
A

array([[[7, 9, 8, 6, 5, 3, 0, 1],
        [1, 2, 2, 9, 3, 7, 3, 0],
        [1, 0, 1, 2, 3, 5, 4, 0],
        [6, 3, 6, 1, 5, 1, 5, 5]]])

In [25]:
B

array([[[0, 6, 5, 0],
        [0, 8, 9, 2],
        [2, 4, 3, 7],
        [6, 5, 5, 9]]])

In [26]:
AR

array([[[[7, 9],
         [8, 6],
         [5, 3],
         [0, 1]],

        [[1, 2],
         [2, 9],
         [3, 7],
         [3, 0]],

        [[1, 0],
         [1, 2],
         [3, 5],
         [4, 0]],

        [[6, 3],
         [6, 1],
         [5, 1],
         [5, 5]]]])

In [27]:
BR

array([[[[0],
         [6],
         [5],
         [0]],

        [[0],
         [8],
         [9],
         [2]],

        [[2],
         [4],
         [3],
         [7]],

        [[6],
         [5],
         [5],
         [9]]]])

In [32]:
# let's do BR.T @ A
# BR.T has shape of (1,4,1,4) and AR has (1,4,4,2) -> (1,4,1,2)

R = np.matmul(np.transpose(BR, (0,1,3,2)), AR)
R

array([[[[ 73,  51]],

        [[ 49, 135]],

        [[ 43,  23]],

        [[136,  73]]]])

In [35]:
BR.shape, AR.shape

((1, 4, 4, 1), (1, 4, 4, 2))

In [37]:
# using einsum 
# B: (ijkl) -> B.T:(ijlk)
# A: (ijkt) -> (ijkt)
# B.T @ A -> (ijlt)

R = np.einsum("ijkl,ijkt -> ijlt",BR,AR)
R

array([[[[ 73,  51]],

        [[ 49, 135]],

        [[ 43,  23]],

        [[136,  73]]]])