In [46]:
import numpy as np
import sympy as sp 
from sympy import assoc_legendre
import matplotlib.pyplot as plt

* If we consider the $B_x$ component of the field

$\hspace{1cm} \begin{bmatrix}
    B^{(x)}_1\\
    B^{(x)}_2\\
    B^{(x)}_3\\
    .\\
    .\\
    B^{(x)}_m
    \end{bmatrix} = \begin{bmatrix}
    0 & 0 & 1 & y_1 & 0 &-\frac{x_1}{2} & z_1 & x_1\\
    0 & 0 & 1 & y_2 & 0 &-\frac{x_2}{2} & z_2 & x_2\\
    0 & 0 & 1 & y_3 & 0 &-\frac{x_3}{2} & z_3 & x_3\\
    . & . & . & . & . & . & . & .\\
    . & . & . & . & . & . & . & .\\
    0 & 0 & 1 & y_m & 0 &-\frac{x_m}{2} & z_m & x_m\\
    \end{bmatrix} \begin{bmatrix}
    a_{0,-1}\\
    a_{0,0}\\
    a_{0,1}\\
    .\\
    a_{1,1}\\
    a_{1,2}
    \end{bmatrix} 
    $ 

* If we consider the $B_y$ component of the field

$\hspace{1cm} \begin{bmatrix}
    B^{(y)}_1\\
    B^{(y)}_2\\
    B^{(y)}_3\\
    .\\
    .\\
    B^{(y)}_m
    \end{bmatrix} = \begin{bmatrix}
    1 & 0 & 0 & x_1 & z_1 &-\frac{y_1}{2} & 0 & y_1\\
    1 & 0 & 0 & x_2 & z_2 &-\frac{y_2}{2} & 0 & y_2\\
    1 & 0 & 0 & x_3 & z_3 &-\frac{y_3}{2} & 0 & y_3\\
    . & . & . & . & . & . & . & .\\
    . & . & . & . & . & . & . & .\\
    1 & 0 & 0 & x_m & z_m &-\frac{y_m}{2} & 0 & y_m\\
    \end{bmatrix} \begin{bmatrix}
    a_{0,-1}\\
    a_{0,0}\\
    a_{0,1}\\
    .\\
    a_{1,1}\\
    a_{1,2}
    \end{bmatrix} 
    $ 

* If we consider the $B_z$ component of the field

$\hspace{1cm} \begin{bmatrix}
    B^{(z)}_1\\
    B^{(z)}_2\\
    B^{(z)}_3\\
    .\\
    .\\
    B^{(z)}_m
    \end{bmatrix} = \begin{bmatrix}
    0 & 1 & 0 & 0 & y_1 & z_1 & x_1 & 0\\
    0 & 1 & 0 & 0 & y_2 & z_2 & x_2 & 0\\
    0 & 1 & 0 & 0 & y_3 & z_3 & x_3 & 0\\
    . & . & . & . & . & . & . & .\\
    . & . & . & . & . & . & . & .\\
    0 & 1 & 0 & 0 & y_m & z_m & x_m & 0\\
    \end{bmatrix} \begin{bmatrix}
    a_{0,-1}\\
    a_{0,0}\\
    a_{0,1}\\
    .\\
    a_{1,1}\\
    a_{1,2}
    \end{bmatrix} 
    $ 

In [47]:
from harmonic_poly import basis_upto_order

In [48]:
# get the haronic polynomials of order 3 (note this is little expensive operation)
l = 3
Phi_x,Phi_y,Phi_z = basis_upto_order(l)

In [49]:
# create a mesh grid to evalute basis function on 
length = np.linspace(-1,1,11)
xv,yv,zv= np.meshgrid(length,length,length)

In [ ]:
# this is a helper function to get the total number of basis functions (upto order l)
def get_no_of_poly(l):
    sum = 0
    sum_arry = [sum]
    for i in range(l+1):
        sum += 2*(i+1) + 1
        sum_arry.append(sum)
    return sum_arry[-1]

m = get_no_of_poly(l)
n = xv.flatten().shape[0]
print(n,m)

In [123]:
# this evaluate basis functions(upto order l) on numpy meshgrid 
def get_Phi_upto(l,xv,yv,zv):
    Phi_xx = Phi_x(xv,yv,zv)
    Phi_yy = Phi_y(xv,yv,zv)
    Phi_zz = Phi_z(xv,yv,zv)
    
    m = get_no_of_poly(l)
    n = xv.flatten().shape[0]
    Phi = np.zeros((3,n,m))
    for i in range(m):
        Phi[0,:,i] = np.array(Phi_xx[i]).flatten()
        Phi[1,:,i] = np.array(Phi_yy[i]).flatten()
        Phi[2,:,i] = np.array(Phi_zz[i]).flatten()
    return Phi[0],Phi[1],Phi[2]

In [124]:
Phi_xx,Phi_yy,Phi_zz = get_Phi_upto(l,xv,yv,zv)

In [125]:
Phi_xx

array([[ 0.  ,  0.  ,  1.  , ..., -2.  , -0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , ..., -0.92, -0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , ..., -0.08, -0.  ,  2.  ],
       ...,
       [ 0.  ,  0.  ,  1.  , ...,  0.08,  0.  , -2.  ],
       [ 0.  ,  0.  ,  1.  , ...,  0.92,  0.  , -2.  ],
       [ 0.  ,  0.  ,  1.  , ...,  2.  ,  0.  , -2.  ]])

In [126]:
Phi_yy

array([[ 1.  ,  0.  ,  0.  , ...,  2.  ,  6.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , ...,  0.92,  4.8 ,  2.  ],
       [ 1.  ,  0.  ,  0.  , ...,  0.08,  3.6 ,  2.  ],
       ...,
       [ 1.  ,  0.  ,  0.  , ..., -0.08, -3.6 , -2.  ],
       [ 1.  ,  0.  ,  0.  , ..., -0.92, -4.8 , -2.  ],
       [ 1.  ,  0.  ,  0.  , ..., -2.  , -6.  , -2.  ]])

In [127]:
Phi_zz

array([[ 0.,  1.,  0., ..., -0.,  2.,  0.],
       [ 0.,  1.,  0., ..., -0.,  2.,  0.],
       [ 0.,  1.,  0., ..., -0.,  2.,  0.],
       ...,
       [ 0.,  1.,  0., ...,  0., -2.,  0.],
       [ 0.,  1.,  0., ...,  0., -2.,  0.],
       [ 0.,  1.,  0., ...,  0., -2.,  0.]])

In [128]:
# this select a given harmonic from a list of harmonics (evaluated on a meshgrid)
def get_slected_harmonic(l,m):
    sum = 0
    sum_arry = [sum]
    for i in range(l+1):
        sum += 2*(i+1) + 1
        sum_arry.append(sum)
    idx = sum_arry[l] + l + 1 + m
    return Phi_xx[:,idx],Phi_yy[:,idx],Phi_zz[:,idx]

Phi_xxx,Phi_yyy,Phi_zzz = get_slected_harmonic(1,0)
Phi_xxx

array([ 0.5,  0.5,  0.5, ..., -0.5, -0.5, -0.5])